# Generated by Django 3.2.9 on 2022-09-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='id_fut',
            field=models.IntegerField(null=True),
        ),
    ]
